# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main2.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1261, 844)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.splitter_3 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_3.setGeometry(QtCore.QRect(10, 10, 1221, 791))
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.splitter = QtWidgets.QSplitter(self.splitter_3)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.groupBox = QtWidgets.QGroupBox(self.splitter)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.tableView_2 = QtWidgets.QTableView(self.groupBox)
        self.tableView_2.setObjectName("tableView_2")
        self.horizontalLayout_18.addWidget(self.tableView_2)
        self.groupBox_2 = QtWidgets.QGroupBox(self.splitter)
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.splitter_2 = QtWidgets.QSplitter(self.splitter_3)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.groupBox_4 = QtWidgets.QGroupBox(self.splitter_2)
        self.groupBox_4.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.groupBox_4.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.tableView = QtWidgets.QTableView(self.groupBox_4)
        self.tableView.setObjectName("tableView")
        self.horizontalLayout_17.addWidget(self.tableView)
        self.groupBox_3 = QtWidgets.QGroupBox(self.splitter_2)
        self.groupBox_3.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_3.setObjectName("groupBox_3")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 280, 330, 22))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_14 = QtWidgets.QLabel(self.layoutWidget)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_7.addWidget(self.label_14)
        self.label_18 = QtWidgets.QLabel(self.layoutWidget)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_7.addWidget(self.label_18)
        self.doubleSpinBox_10 = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_10.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_10.setDecimals(4)
        self.doubleSpinBox_10.setMinimum(-999999999999.0)
        self.doubleSpinBox_10.setMaximum(99999999999999.0)
        self.doubleSpinBox_10.setSingleStep(0.01)
        self.doubleSpinBox_10.setProperty("value", 0.93)
        self.doubleSpinBox_10.setObjectName("doubleSpinBox_10")
        self.horizontalLayout_7.addWidget(self.doubleSpinBox_10)
        self.label_19 = QtWidgets.QLabel(self.layoutWidget)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_7.addWidget(self.label_19)
        self.label_20 = QtWidgets.QLabel(self.layoutWidget)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_7.addWidget(self.label_20)
        self.label_21 = QtWidgets.QLabel(self.layoutWidget)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_7.addWidget(self.label_21)
        self.doubleSpinBox_11 = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_11.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_11.setDecimals(4)
        self.doubleSpinBox_11.setMinimum(-999999999999.0)
        self.doubleSpinBox_11.setMaximum(99999999999999.0)
        self.doubleSpinBox_11.setSingleStep(0.01)
        self.doubleSpinBox_11.setProperty("value", 551.6)
        self.doubleSpinBox_11.setObjectName("doubleSpinBox_11")
        self.horizontalLayout_7.addWidget(self.doubleSpinBox_11)
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget_2.setGeometry(QtCore.QRect(20, 310, 348, 22))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_22 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_8.addWidget(self.label_22)
        self.label_23 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_8.addWidget(self.label_23)
        self.doubleSpinBox_12 = QtWidgets.QDoubleSpinBox(self.layoutWidget_2)
        self.doubleSpinBox_12.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_12.setDecimals(4)
        self.doubleSpinBox_12.setMinimum(-999999999999.0)
        self.doubleSpinBox_12.setMaximum(99999999999999.0)
        self.doubleSpinBox_12.setSingleStep(0.01)
        self.doubleSpinBox_12.setProperty("value", 1947.8)
        self.doubleSpinBox_12.setObjectName("doubleSpinBox_12")
        self.horizontalLayout_8.addWidget(self.doubleSpinBox_12)
        self.label_24 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_8.addWidget(self.label_24)
        self.label_25 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_8.addWidget(self.label_25)
        self.label_26 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_8.addWidget(self.label_26)
        self.doubleSpinBox_13 = QtWidgets.QDoubleSpinBox(self.layoutWidget_2)
        self.doubleSpinBox_13.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_13.setDecimals(4)
        self.doubleSpinBox_13.setMinimum(-99999999999.0)
        self.doubleSpinBox_13.setMaximum(99999999999999.0)
        self.doubleSpinBox_13.setSingleStep(0.01)
        self.doubleSpinBox_13.setProperty("value", -13746.0)
        self.doubleSpinBox_13.setObjectName("doubleSpinBox_13")
        self.horizontalLayout_8.addWidget(self.doubleSpinBox_13)
        self.layoutWidget_9 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget_9.setGeometry(QtCore.QRect(20, 340, 342, 22))
        self.layoutWidget_9.setObjectName("layoutWidget_9")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.layoutWidget_9)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_50 = QtWidgets.QLabel(self.layoutWidget_9)
        self.label_50.setObjectName("label_50")
        self.horizontalLayout_15.addWidget(self.label_50)
        self.label_51 = QtWidgets.QLabel(self.layoutWidget_9)
        self.label_51.setObjectName("label_51")
        self.horizontalLayout_15.addWidget(self.label_51)
        self.doubleSpinBox_22 = QtWidgets.QDoubleSpinBox(self.layoutWidget_9)
        self.doubleSpinBox_22.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_22.setDecimals(4)
        self.doubleSpinBox_22.setMinimum(-999999999999.0)
        self.doubleSpinBox_22.setMaximum(99999999999999.0)
        self.doubleSpinBox_22.setSingleStep(0.01)
        self.doubleSpinBox_22.setProperty("value", 0.65)
        self.doubleSpinBox_22.setObjectName("doubleSpinBox_22")
        self.horizontalLayout_15.addWidget(self.doubleSpinBox_22)
        self.label_52 = QtWidgets.QLabel(self.layoutWidget_9)
        self.label_52.setObjectName("label_52")
        self.horizontalLayout_15.addWidget(self.label_52)
        self.label_53 = QtWidgets.QLabel(self.layoutWidget_9)
        self.label_53.setObjectName("label_53")
        self.horizontalLayout_15.addWidget(self.label_53)
        self.label_54 = QtWidgets.QLabel(self.layoutWidget_9)
        self.label_54.setObjectName("label_54")
        self.horizontalLayout_15.addWidget(self.label_54)
        self.doubleSpinBox_23 = QtWidgets.QDoubleSpinBox(self.layoutWidget_9)
        self.doubleSpinBox_23.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_23.setDecimals(4)
        self.doubleSpinBox_23.setMinimum(-99999999999.0)
        self.doubleSpinBox_23.setMaximum(99999999999999.0)
        self.doubleSpinBox_23.setSingleStep(0.01)
        self.doubleSpinBox_23.setProperty("value", 1048.9)
        self.doubleSpinBox_23.setObjectName("doubleSpinBox_23")
        self.horizontalLayout_15.addWidget(self.doubleSpinBox_23)
        self.layoutWidget_10 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget_10.setGeometry(QtCore.QRect(20, 190, 431, 22))
        self.layoutWidget_10.setObjectName("layoutWidget_10")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.layoutWidget_10)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_55 = QtWidgets.QLabel(self.layoutWidget_10)
        self.label_55.setObjectName("label_55")
        self.horizontalLayout_16.addWidget(self.label_55)
        self.label_56 = QtWidgets.QLabel(self.layoutWidget_10)
        self.label_56.setObjectName("label_56")
        self.horizontalLayout_16.addWidget(self.label_56)
        self.label_64 = QtWidgets.QLabel(self.layoutWidget_10)
        self.label_64.setObjectName("label_64")
        self.horizontalLayout_16.addWidget(self.label_64)
        self.doubleSpinBox_24 = QtWidgets.QDoubleSpinBox(self.layoutWidget_10)
        self.doubleSpinBox_24.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_24.setDecimals(5)
        self.doubleSpinBox_24.setMinimum(-9999999.0)
        self.doubleSpinBox_24.setMaximum(99999999999999.0)
        self.doubleSpinBox_24.setSingleStep(0.01)
        self.doubleSpinBox_24.setProperty("value", 0.0045)
        self.doubleSpinBox_24.setObjectName("doubleSpinBox_24")
        self.horizontalLayout_16.addWidget(self.doubleSpinBox_24)
        self.label_57 = QtWidgets.QLabel(self.layoutWidget_10)
        self.label_57.setObjectName("label_57")
        self.horizontalLayout_16.addWidget(self.label_57)
        self.label_58 = QtWidgets.QLabel(self.layoutWidget_10)
        self.label_58.setObjectName("label_58")
        self.horizontalLayout_16.addWidget(self.label_58)
        self.label_59 = QtWidgets.QLabel(self.layoutWidget_10)
        self.label_59.setObjectName("label_59")
        self.horizontalLayout_16.addWidget(self.label_59)
        self.label_60 = QtWidgets.QLabel(self.layoutWidget_10)
        self.label_60.setObjectName("label_60")
        self.horizontalLayout_16.addWidget(self.label_60)
        self.label_61 = QtWidgets.QLabel(self.layoutWidget_10)
        self.label_61.setObjectName("label_61")
        self.horizontalLayout_16.addWidget(self.label_61)
        self.label_62 = QtWidgets.QLabel(self.layoutWidget_10)
        self.label_62.setObjectName("label_62")
        self.horizontalLayout_16.addWidget(self.label_62)
        self.label_63 = QtWidgets.QLabel(self.layoutWidget_10)
        self.label_63.setObjectName("label_63")
        self.horizontalLayout_16.addWidget(self.label_63)
        self.label_65 = QtWidgets.QLabel(self.layoutWidget_10)
        self.label_65.setObjectName("label_65")
        self.horizontalLayout_16.addWidget(self.label_65)
        self.doubleSpinBox_25 = QtWidgets.QDoubleSpinBox(self.layoutWidget_10)
        self.doubleSpinBox_25.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_25.setDecimals(5)
        self.doubleSpinBox_25.setMinimum(-9999999999.0)
        self.doubleSpinBox_25.setMaximum(99999999999999.0)
        self.doubleSpinBox_25.setSingleStep(0.01)
        self.doubleSpinBox_25.setProperty("value", 0.008)
        self.doubleSpinBox_25.setObjectName("doubleSpinBox_25")
        self.horizontalLayout_16.addWidget(self.doubleSpinBox_25)
        self.label_66 = QtWidgets.QLabel(self.layoutWidget_10)
        self.label_66.setObjectName("label_66")
        self.horizontalLayout_16.addWidget(self.label_66)
        self.label_67 = QtWidgets.QLabel(self.layoutWidget_10)
        self.label_67.setObjectName("label_67")
        self.horizontalLayout_16.addWidget(self.label_67)
        self.label_68 = QtWidgets.QLabel(self.layoutWidget_10)
        self.label_68.setObjectName("label_68")
        self.horizontalLayout_16.addWidget(self.label_68)
        self.label_69 = QtWidgets.QLabel(self.layoutWidget_10)
        self.label_69.setObjectName("label_69")
        self.horizontalLayout_16.addWidget(self.label_69)
        self.doubleSpinBox_26 = QtWidgets.QDoubleSpinBox(self.layoutWidget_10)
        self.doubleSpinBox_26.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_26.setDecimals(5)
        self.doubleSpinBox_26.setMinimum(-9999999999.0)
        self.doubleSpinBox_26.setMaximum(99999999999999.0)
        self.doubleSpinBox_26.setSingleStep(0.01)
        self.doubleSpinBox_26.setProperty("value", 12.0)
        self.doubleSpinBox_26.setObjectName("doubleSpinBox_26")
        self.horizontalLayout_16.addWidget(self.doubleSpinBox_26)
        self.widget = QtWidgets.QWidget(self.groupBox_3)
        self.widget.setGeometry(QtCore.QRect(20, 220, 208, 22))
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9)
        self.label_13 = QtWidgets.QLabel(self.widget)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_3.addWidget(self.label_13)
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_3.addWidget(self.label_10)
        self.doubleSpinBox_7 = QtWidgets.QDoubleSpinBox(self.widget)
        self.doubleSpinBox_7.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_7.setDecimals(4)
        self.doubleSpinBox_7.setMaximum(99999999999999.0)
        self.doubleSpinBox_7.setSingleStep(0.01)
        self.doubleSpinBox_7.setProperty("value", 304800.0)
        self.doubleSpinBox_7.setObjectName("doubleSpinBox_7")
        self.horizontalLayout_3.addWidget(self.doubleSpinBox_7)
        self.widget1 = QtWidgets.QWidget(self.groupBox_3)
        self.widget1.setGeometry(QtCore.QRect(20, 50, 154, 22))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.widget1)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.db_bottom = QtWidgets.QDoubleSpinBox(self.widget1)
        self.db_bottom.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.db_bottom.setMaximum(99999999999999.0)
        self.db_bottom.setSingleStep(0.01)
        self.db_bottom.setProperty("value", 3450.0)
        self.db_bottom.setObjectName("db_bottom")
        self.horizontalLayout_4.addWidget(self.db_bottom)
        self.widget2 = QtWidgets.QWidget(self.groupBox_3)
        self.widget2.setGeometry(QtCore.QRect(20, 70, 154, 22))
        self.widget2.setObjectName("widget2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(self.widget2)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.db_top = QtWidgets.QDoubleSpinBox(self.widget2)
        self.db_top.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.db_top.setMaximum(99999999999999.0)
        self.db_top.setSingleStep(0.01)
        self.db_top.setProperty("value", 3520.0)
        self.db_top.setObjectName("db_top")
        self.horizontalLayout_5.addWidget(self.db_top)
        self.widget3 = QtWidgets.QWidget(self.groupBox_3)
        self.widget3.setGeometry(QtCore.QRect(20, 250, 330, 22))
        self.widget3.setObjectName("widget3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget3)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_11 = QtWidgets.QLabel(self.widget3)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_6.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.widget3)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_6.addWidget(self.label_12)
        self.doubleSpinBox_8 = QtWidgets.QDoubleSpinBox(self.widget3)
        self.doubleSpinBox_8.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_8.setDecimals(4)
        self.doubleSpinBox_8.setMinimum(-999999999999.0)
        self.doubleSpinBox_8.setMaximum(99999999999999.0)
        self.doubleSpinBox_8.setSingleStep(0.01)
        self.doubleSpinBox_8.setProperty("value", 0.71)
        self.doubleSpinBox_8.setObjectName("doubleSpinBox_8")
        self.horizontalLayout_6.addWidget(self.doubleSpinBox_8)
        self.label_15 = QtWidgets.QLabel(self.widget3)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_6.addWidget(self.label_15)
        self.label_16 = QtWidgets.QLabel(self.widget3)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_6.addWidget(self.label_16)
        self.label_17 = QtWidgets.QLabel(self.widget3)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_6.addWidget(self.label_17)
        self.doubleSpinBox_9 = QtWidgets.QDoubleSpinBox(self.widget3)
        self.doubleSpinBox_9.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_9.setDecimals(4)
        self.doubleSpinBox_9.setMinimum(-999999999999.0)
        self.doubleSpinBox_9.setMaximum(99999999999999.0)
        self.doubleSpinBox_9.setSingleStep(0.01)
        self.doubleSpinBox_9.setProperty("value", 1602.3)
        self.doubleSpinBox_9.setObjectName("doubleSpinBox_9")
        self.horizontalLayout_6.addWidget(self.doubleSpinBox_9)
        self.widget4 = QtWidgets.QWidget(self.groupBox_3)
        self.widget4.setGeometry(QtCore.QRect(480, 230, 124, 141))
        self.widget4.setObjectName("widget4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget4)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pb_load = QtWidgets.QPushButton(self.widget4)
        self.pb_load.setObjectName("pb_load")
        self.verticalLayout_2.addWidget(self.pb_load)
        self.pb_cal = QtWidgets.QPushButton(self.widget4)
        self.pb_cal.setObjectName("pb_cal")
        self.verticalLayout_2.addWidget(self.pb_cal)
        self.pb_paint = QtWidgets.QPushButton(self.widget4)
        self.pb_paint.setObjectName("pb_paint")
        self.verticalLayout_2.addWidget(self.pb_paint)
        self.pb_toexcel = QtWidgets.QPushButton(self.widget4)
        self.pb_toexcel.setObjectName("pb_toexcel")
        self.verticalLayout_2.addWidget(self.pb_toexcel)
        self.pb_topic = QtWidgets.QPushButton(self.widget4)
        self.pb_topic.setObjectName("pb_topic")
        self.verticalLayout_2.addWidget(self.pb_topic)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1261, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "页岩油储层可压性评价软件"))
        self.groupBox.setTitle(_translate("MainWindow", "储层参数计算结果"))
        self.groupBox_2.setTitle(_translate("MainWindow", "岩石力学参数曲线"))
        self.groupBox_4.setTitle(_translate("MainWindow", "测井资料"))
        self.groupBox_3.setTitle(_translate("MainWindow", "井场参数输入"))
        self.label_14.setText(_translate("MainWindow", "Vp45"))
        self.label_18.setText(_translate("MainWindow", "="))
        self.label_19.setText(_translate("MainWindow", "*"))
        self.label_20.setText(_translate("MainWindow", "Vp0"))
        self.label_21.setText(_translate("MainWindow", "+"))
        self.label_22.setText(_translate("MainWindow", "Vs0"))
        self.label_23.setText(_translate("MainWindow", "="))
        self.label_24.setText(_translate("MainWindow", "*"))
        self.label_25.setText(_translate("MainWindow", "ln(Vp0)"))
        self.label_26.setText(_translate("MainWindow", "+"))
        self.label_50.setText(_translate("MainWindow", "Vs90"))
        self.label_51.setText(_translate("MainWindow", "="))
        self.label_52.setText(_translate("MainWindow", "*"))
        self.label_53.setText(_translate("MainWindow", "Vs0"))
        self.label_54.setText(_translate("MainWindow", "+"))
        self.label_55.setText(_translate("MainWindow", "St"))
        self.label_56.setText(_translate("MainWindow", "="))
        self.label_64.setText(_translate("MainWindow", "["))
        self.label_57.setText(_translate("MainWindow", "E"))
        self.label_58.setText(_translate("MainWindow", "*"))
        self.label_59.setText(_translate("MainWindow", "（"))
        self.label_60.setText(_translate("MainWindow", "1"))
        self.label_61.setText(_translate("MainWindow", "-"))
        self.label_62.setText(_translate("MainWindow", "Vsh"))
        self.label_63.setText(_translate("MainWindow", "）"))
        self.label_65.setText(_translate("MainWindow", "+"))
        self.label_66.setText(_translate("MainWindow", "E"))
        self.label_67.setText(_translate("MainWindow", "Vsh"))
        self.label_68.setText(_translate("MainWindow", "]"))
        self.label_69.setText(_translate("MainWindow", "/"))
        self.label_3.setText(_translate("MainWindow", "Vp0"))
        self.label_7.setText(_translate("MainWindow", "="))
        self.label_8.setText(_translate("MainWindow", "1"))
        self.label_9.setText(_translate("MainWindow", "/"))
        self.label_13.setText(_translate("MainWindow", "AC"))
        self.label_10.setText(_translate("MainWindow", "*"))
        self.label_2.setText(_translate("MainWindow", "底深："))
        self.label.setText(_translate("MainWindow", "顶深："))
        self.label_11.setText(_translate("MainWindow", "Vp90"))
        self.label_12.setText(_translate("MainWindow", "="))
        self.label_15.setText(_translate("MainWindow", "*"))
        self.label_16.setText(_translate("MainWindow", "Vp0"))
        self.label_17.setText(_translate("MainWindow", "+"))
        self.pb_load.setText(_translate("MainWindow", "导入测井资料"))
        self.pb_cal.setText(_translate("MainWindow", "计算岩石力学参数"))
        self.pb_paint.setText(_translate("MainWindow", "绘制力学参数曲线"))
        self.pb_toexcel.setText(_translate("MainWindow", "导出数据到excel文件"))
        self.pb_topic.setText(_translate("MainWindow", "导出图片"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
